name: Install dependencies
description: Use conan for installing dependencies

inputs:
  build_type:
    required: true
  compiler:
    required: true

runs:
  using: composite
  steps:

    - name: Cache Conan packages
      uses: actions/cache@v6
      with:
        path: ~/.conan2
        key: conan-${{ runner.os }}-${{ inputs.build_type }}-${{ inputs.compiler }}-${{ hashFiles('conanfile.py', 'conan.lock') }}
        restore-keys: |
          conan-${{ runner.os }}-${{ inputs.build_type }}-${{ inputs.compiler }}-
    - name: Create Conan profile
      shell: bash
      run: |
        conan profile detect --force

    - name: Install Conan dependencies
      shell: bash
      run: |
        conan install . \
          --lockfile=conan.lock \
          --build=missing \
          -s build_type=${{ inputs.build_type }} \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True

