name: Quality checks
description: Run linting and static analysis for checking for common errors


inputs:
  build_type:
    required: true

runs:
  using: composite
  steps:
    - name: Run cppcheck
      shell: bash
      run: |
        cppcheck \
          --project=build/${{ inputs.build_type }}/compile_commands.json \
          --enable=warning,style,performance,portability \
          --inconclusive \
          --exclude=*/proto/*


    - name: Run clang-tidy
      shell: bash
      run: |
        run-clang-tidy \
          -p build/${{ inputs.build_type }} \
          '^(?!.*\/proto\/).*'
