name: Quality checks
description: Run linting and static analysis for checking for common errors


inputs:
  build_type:
    required: true

runs:
  using: composite
  steps:
    - name: Enable compiler problem matcher
      shell: bash
      run: |
        echo "::add-matcher::${{ github.workspace }}/.github/problem-matchers/cpp.json"

    - name: Run cppcheck
      shell: bash
      run: |
        cppcheck \
          --project=build/${{ inputs.build_type }}/compile_commands.json \
          --enable=warning,style,performance,portability \
          --inconclusive \
          --suppress='*:/proto/*'



    - name: Run clang-tidy
      shell: bash
      run: |
        run-clang-tidy \
          -p build/${{ inputs.build_type }} \
          '^(?!.*\/proto\/).*'


    - name: Remove problem matcher
      if: always()
      shell: bash
      run: |
        echo "::remove-matcher owner=cpp::"
