name: Quality checks
description: Run linting and static analysis for checking for common errors


runs:
  using: composite
  steps:
    - name: Run cppcheck
      shell: bash
      run: |
        cppcheck \
          --project=build/Release/compile_commands.json \
          --enable=warning,style,performance,portability \
          --inconclusive 


    - name: Run clang-tidy
      shell: bash
      run: |
        run-clang-tidy \
          -p build/Release

