# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Build ${{ matrix.compiler}}-${{ matrix.build_type }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
          - clang
        build_type:
          - Debug
          - Release

    steps:
      - uses: actions/checkout@v4

      - name: Setup cpp environment
        uses: ./.github/actions/setup-cpp

      - name: Check formatting
        if: ${{ matrix.compiler }} == 'clang' && ${{ matrix.build_type }} == 'Debug'
        uses: ./.github/actions/audit

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          build_type: ${{ matrix.build_type }}
          compiler: ${{ matrix.compiler }}

      - name: Build cpp
        uses: ./.github/actions/build-cpp
        with:
          compiler: ${{ matrix.compiler }}
          build_type: ${{ matrix.build_type }}

      - name: Static analysis
        if: ${{ matrix.compiler }} == 'clang' && ${{ matrix.build_type }} == 'Debug'
        uses: ./.github/actions/quality-check



